# building a layer

In [1]:
def linear_layer(inputs, weights, bias):
    layer_output = []
    for neuron_weights, neuron_bias in zip(weights, bias):
        neuron_output = 0
        for input, weight in zip(inputs, neuron_weights):
            neuron_output += input * weight
        neuron_output += neuron_bias
        layer_output.append(neuron_output)

    return layer_output



 The neuron layer consists of 3 neurons, each receiving 3 inputs. 

The inputs to the layer are [1, 2, 3]. The weights connecting the inputs to the neurons are as follows:
- Neuron 1: [1, 2, 3]
- Neuron 2: [4, 5, 6]
- Neuron 3: [7, 8, 9]

Each neuron also has a bias value of 1.

To compute the output of each neuron, the inputs are multiplied by their corresponding weights, and the bias is added. The outputs of the neurons are as follows:
- Neuron 1 output: [output value]
- Neuron 2 output: [output value]
- Neuron 3 output: [output value]


In [2]:
inputs = [1, 2, 3]
weights = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
bias = [1, 1, 1]

print(linear_layer(inputs, weights, bias))

[15, 33, 51]


In [4]:
import numpy as np

def linear_layer(inputs, weights, bias):
    return np.dot(weights, inputs) + bias #weights should be the first argument because we want the output to be the same shape as the weights

inputs = np.array([1, 2, 3])
weights = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
bias = np.array([1, 1, 1])

print(linear_layer(inputs, weights, bias))

[15 33 51]


In [5]:
inputs = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]
weights = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]
bias = [1, 1, 1]
# (3,4) x (3,4) can't be done because the number of columns in the first matrix is not equal to the number of rows in the second matrix
print(linear_layer(inputs, weights, bias)) #this will not work because the shapes of the inputs and weights are not compatible

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [8]:
#need for transposing the weights

def linear_layer(inputs, weights, bias):
    return np.dot(inputs, np.array(weights).T) + bias

inputs = [[1,2,3,4], [5,6,7,8], [9,10,11,12]] #batch of 3 inputs
weights = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]

print(linear_layer(inputs, weights, bias))

[[ 31  71 111]
 [ 71 175 279]
 [111 279 447]]


# Adding another layer


In [13]:
inputs = [[1,2,3,4], [5,6,7,8], [9,10,11,12]] #batch of 3 inputs
weights = [[1,2,3,4], [5,6,7,8], [9,10,11,12]]
bias = [1, 1, 1]

weights2 = [[13,14,15], [16,17,18], [19,20,21]]
bias2 = [1, -1, 0.5]

layer_output1 = linear_layer(inputs, weights, bias)
layer_output2 = linear_layer(layer_output1, weights2, bias2)
# print(layer_output1)
print(layer_output2)



[[ 3063.   3700.   4340.5]
 [ 7559.   9132.  10708.5]
 [12055.  14564.  17076.5]]


# converting to a class object

In [21]:
class Dense_layer:
    
    def __init__(self,n_inputs, n_neurons):
        # note that n_inputs becomes the number of rows and n_neurons becomes the number of columns to avoid transposing the weights
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons) # 0.10 is a scaling factor
        self.bias = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.bias
        

In [23]:
np.random.seed(0)
X = [[1,2,3,4], [5,6,7,8], [9,10,11,12]] #batch of 3 inputs

layer1 = Dense_layer(4, 5)
layer2 = Dense_layer(5, 2)

layer1.forward(X)
# print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)

[[ 0.12848393 -0.11256537]
 [ 0.39280849 -0.19706153]
 [ 0.65713306 -0.2815577 ]]
